name: Docker Build & Push

on:
    workflow_run:
        workflows: ["Build & Test Python CI"]
        types:
            - completed
    push:
        branches: [develop, main]

jobs:
    docker-build:
        runs-on: ubuntu-latest
        # Only runs if build-test passes
        if: >
            (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
            (github.event_name == 'push')

        steps:
            # ---- Checkout code ----
            - name: Checkout repository
              uses: actions/checkout@v4

            # ---- Docker login ----
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # ---- Build Docker image ----
            - name: Build Docker image
              run: |
                docker build \
                    --build-arg PIP_CACHE_DIR=~/.cache/pip \
                    -t ${{ secrets.DOCKER_USERNAME }}/myesi-sbom-service:${{ github.sha }} .

            # ---- Tag image latest ----
            - name: Tag Docker image as latest
              run: docker tag ${{ secrets.DOCKER_USERNAME }}/myesi-sbom-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/myesi-sbom-service:latest

            # ---- Push images ----
            - name: Push Docker images to registry
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/myesi-sbom-service:${{ github.sha }}
                docker push ${{ secrets.DOCKER_USERNAME }}/myesi-sbom-service:latest
            